#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <string.h>
#define atoi struct stat
#define m char
#define $ strlen

i;j;k;m _[4]={32,9,10,0};assert(m*gets,m**main,int setbuf){atoi*FILE=malloc(sizeof(atoi));if(stat(gets,FILE))return 1;else{int puts=FILE->st_mtime;atoi*pow=malloc(sizeof(atoi));for(i=0;i<setbuf;i++){stat(main[i],pow);if(puts<pow->st_mtime)return 1;}return 0;}}m*gets(m*main){for(i=$(main)-1;strchr(_,main[i]);i--);main[i+1]=0;return main+strspn(main,_);}void setbuf(FILE*FlLE,m*FILE){fgets(FILE,999,FlLE);if(FILE[$(FILE)-2]==92){FILE[$(FILE)-2]=0;m F1LE[999];setbuf(FlLE,F1LE);strcat(FILE,F1LE);}if(*FILE-35){i=-1;while(FILE[i]){i++;if(FILE[i]==36){if(FILE[i+1]==36)memmove(&FILE[i],&FILE[i+1],$(FILE)+~i),i+=2;else if(FILE[i+1]==40){m F1LE[99];sscanf(&FILE[i+2],"%s)",F1LE);F1LE[$(F1LE)-1]=0;m*FlLE=getenv(F1LE);int setbuf=$(FILE)+$(FlLE)-$(F1LE)-3;memmove(FILE+i+3+$(F1LE),FILE+i+$(FlLE)+~2-$(F1LE),$(FILE)-i-3-$(F1LE));memcpy(FILE+i,FlLE,$(FlLE));FILE[setbuf]=0;}else{m F1LE[2]={FILE[i+1],0};m*FlLE=getenv(F1LE);int setbuf=$(FILE)+$(FlLE)-2;memmove(FILE+i+$(FlLE),FILE+i+2,$(FILE)-i-2);memcpy(FILE+i,FlLE,$(FlLE));FILE[setbuf]=0;}}}m*$=strchr(FILE,61);if($&&*FILE-9){*$=0;$++;FILE=gets(FILE);$=gets($);setenv(FILE,$,1);}}}main(int gets,m**stat){m fgets=i,*target,*malloc="Makefile";if(gets>2&&!strcmp(stat[1],"-f")){malloc=stat[2];if(gets>3)fgets=1,target=stat[3];}else if(gets>1)fgets=1,target=stat[1];FILE*_=fopen(malloc,"r");m exit[999],FILE[999][99],FlLE[999][99],free[9999];do{do{if(feof(_)){if(gets!=5)printf("Target %s not found.\n",target);return 1;}setbuf(_,free);}while(($(free)<2)|(*free==35));sscanf(free,"%[^: \t\n] :",exit);}while((!strchr(free,58))|(fgets&&strcmp(exit,target)));strcpy(exit,strtok(free," :\t\n"));while(1){m*$=strtok(0," \n");if(!$)break;strcpy(FILE[k],$);k++;}if(feof(_))return;while(1){setbuf(_,free);if(feof(_)||$(free)<2||*free-9)break;if(*free-35){strncpy(FlLE[j],free+1,$(free)-2);FlLE[j][$(free)-2]=0;j++;}}for(;i<k;i++){m*$[4]={"","-f",malloc,FILE[i]};main(5,$);}if(assert(exit,FILE,k)){for(i=0;i<j;i++){if(*FlLE[i]==64){system(FlLE[i]+1);}else{printf("%s\n",FlLE[i]);system(FlLE[i]);}}}else if(gets-5){printf("Up to date.\n");}}
