#include <stdio.h>
#define all main(){int k = 0;switch(k) {default //I've got 99 problems but a switch ain't one.
#define Makefile
#define gcc printf("Hello, world!\n");
#define x -k;
#define c break;}}

all: Makefile
	gcc -x c Makefile

#ifdef _
clean:
	rm a.out
#endif
